/// Class names of the COCO-trained YOLO11n model, in model output order.
const List<String> cocoLabels = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];

/// Class names of the PKR currency model in model output order, exactly as
/// stored in the trained checkpoint (alphabetical, not numeric).
const List<String> pkrLabels = [
  '10_PKR',
  '100_PKR',
  '1000_PKR',
  '20_PKR',
  '50_PKR',
  '500_PKR',
  '5000_PKR',
];

/// Rupee value of a PKR class label, e.g. '500_PKR' -> 500.
int pkrValue(String label) => int.parse(label.split('_').first);

/// Objects that matter while walking. Anything else is ignored by the
/// obstacle alert mode to keep it quiet.
const Set<String> obstacleLabels = {
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'bus',
  'truck',
  'train',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'dog',
  'cat',
  'horse',
  'cow',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'refrigerator',
  'suitcase',
  'backpack',
  'umbrella',
  'sink',
  'oven',
  'skateboard',
};

/// Moving hazards get a stronger alert.
const Set<String> movingHazards = {
  'car',
  'motorcycle',
  'bus',
  'truck',
  'bicycle',
  'train',
  'horse',
  'cow',
  'dog',
};
